# Generated by Django 5.1.6 on 2025-02-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_age_range_alter_userprofile_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age_range',
        ),
    ]
