# Generated by Django 5.1.6 on 2025-02-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='font_family',
            field=models.CharField(choices=[('serif', 'Merriweather'), ('Roboto', 'Roboto'), ('Lexend', 'Lexend')], default='Roboto', max_length=10),
        ),
    ]
